Repository michalkonecny/robust-plots, pull requests merged in 2020-06, with the labels that each got.

#37 Added many plots support and bounds input
  README.md
  package.json
  spago.dhall
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Canvas/Draw.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Draw/Color.purs
  src/Main.purs
  src/Plot/Commands.purs
  src/Plot/PlotController.purs
  src/Types.purs
Labels: enhancement

#40 Added smoother plots and differentiation
  src/Components/ExpressionInput/Controller.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Expression/Differentiator.purs
  src/Expression/Parser.purs
  src/Expression/Simplifier.purs
  src/Expression/Syntax.purs
  src/Plot/PlotController.purs
  test/Expression/Differentiator/Differentiate.purs
  test/Expression/Differentiator/Differentiator.purs
  test/Expression/Expression.purs
  test/Expression/Parser/Parse.purs
  test/Expression/Simplifier/Simplifier.purs
  test/Expression/Simplifier/Simplify.purs
Labels: enhancement

#43 Added plot labels and reset button
  src/Components/Canvas/Draw.purs
  src/Components/Canvas/Interpreter.purs
  src/Draw/Actions.purs
  src/Draw/Commands.purs
  src/Main.purs
  src/Plot/Commands.purs
  src/Plot/PlotController.purs
Labels: enhancement

#44 Refactored to Rational literal values
  src/Expression/Differentiator.purs
  src/Expression/Evaluator.purs
  src/Expression/Parser.purs
  src/Expression/Simplifier.purs
  src/Expression/Syntax.purs
  src/Expression/VariableMap.purs
  src/IntervalArith/Misc.purs
  test/Expression/Evaluator/Evaluate.purs
  test/Expression/Evaluator/Evaluator.purs
  test/Expression/Expression.purs
  test/Expression/Parser/Parse.purs
  test/Expression/Simplifier/Simplify.purs
  test/Expression/VariableMap/Lookup.purs
  test/Expression/VariableMap/VariableMap.purs
Labels: enhancement

#45 Approx field arithmetic, conversions
  src/IntervalArith/Approx/Approx.purs
  src/IntervalArith/Dyadic.purs
  src/IntervalArith/Misc.purs
  test/Field.purs
  test/IntervalArith/Approx/Approx.purs
  test/IntervalArith/Approx/ShowA.purs
  test/IntervalArith/Dyadic.purs
  test/Order.purs
  test/Ring.purs
  test/TestUtils.purs
Labels: enhancement

#47 Added Sub expression simplification
  src/Components/ExpressionInput/Controller.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Expression/Differentiator.purs
  src/Expression/Error.purs
  src/Expression/Evaluator.purs
  src/Expression/Helper.purs
  src/Expression/Simplifier.purs
  src/Expression/SubExpression.purs
  src/Expression/Syntax.purs
  src/Main.purs
  src/Plot/Commands.purs
  src/Plot/PlotController.purs
  test/Expression/Expression.purs
  test/Expression/Helper.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/Expression/SubExpression/OrderDepencencies.purs
  test/Expression/SubExpression/SplitSubExpressions.purs
  test/Expression/SubExpression/SubExpression.purs
  test/Expression/SubExpression/SubExpressionToVariableMap.purs
  test/Expression/SubExpression/SubstituteSubExpressions.purs
Labels: enhancement

#57 Added evaluation to Approx
  .github/workflows/buildandtest.yml
  package.json
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Expression/Differentiator.purs
  src/Expression/Error.purs
  src/Expression/Evaluator.purs
  src/Expression/SubExpression.purs
  src/Plot/Commands.purs
  src/Plot/Helper.purs
  src/Plot/PlotController.purs
  src/Plot/RoughPlot.purs
  test/Expression/Evaluator/Evaluate.purs
  test/Expression/Evaluator/Evaluator.purs
  test/Expression/Evaluator/RoughEvaluate.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/Expression/SubExpression/RemoveSubExpressions.purs
  test/Expression/SubExpression/SubExpression.purs
Labels: bug, enhancement

#59 Added enclosure based plotting
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Canvas/Canvas.purs
  src/Components/Canvas/Controller.purs
  src/Main.purs
  src/Plot/Commands.purs
  src/Plot/GridLines.purs
  src/Plot/Helper.purs
  src/Plot/Pan.purs
  src/Plot/PlotController.purs
  src/Plot/RobustPlot.purs
  src/Plot/RoughPlot.purs
  src/Plot/Zoom.purs
  src/Types.purs
Labels: enhancement

#61 Added batch operation support
  src/Components/Canvas/Canvas.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Main.purs
  src/Plot/Commands.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
  src/Plot/Queue.purs
  src/Plot/RobustPlot.purs
  src/Plot/RoughPlot.purs
  src/Types.purs
  test/Main.purs
  test/Plot/JobBatcher/AddPlot.purs
  test/Plot/JobBatcher/CancelAll.purs
  test/Plot/JobBatcher/CancelWithBatchId.purs
  test/Plot/JobBatcher/ClearCancelled.purs
  test/Plot/JobBatcher/HasJobs.purs
  test/Plot/JobBatcher/InitialJobQueue.purs
  test/Plot/JobBatcher/IsCancelled.purs
  test/Plot/JobBatcher/JobBatcher.purs
  test/Plot/JobBatcher/SetRunning.purs
  test/Plot/Plot.purs
Labels: enhancement

#69 Fixed Rational input bug
  src/Components/BoundsInput/BoundsInput.purs
  src/Expression/Parser.purs
  test/Expression/Parser/FoldIntoRational.purs
  test/Expression/Parser/Parse.purs
  test/Expression/Parser/Parser.purs
Labels: bug

#70 Added Batch and Segment input
  src/Components/BatchInput/BatchInput.purs
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Plot/Commands.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
  src/Plot/RobustPlot.purs
  test/Plot/JobBatcher/AddPlot.purs
Labels: enhancement

#71 Pan and Zoom delay robust plot
  src/Components/Canvas/Canvas.purs
  src/Components/Main/Action.purs
Labels: enhancement

#72 Added plot controls and error handling
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Expression/SubExpression.purs
  src/Plot/JobBatcher.purs
  src/Plot/RobustPlot.purs
  src/Plot/RoughPlot.purs
  test/Expression/Evaluator/RoughEvaluate.purs
  test/Expression/Parser/Parse.purs
  test/Expression/Simplifier/Simplify.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/Expression/SubExpression/OrderDepencencies.purs
  test/Plot/JobBatcher/CancelWithBatchId.purs
  test/Plot/JobBatcher/JobBatcher.purs
Labels: enhancement

#75 Added interconnected parallelogram plot
  src/Expression/Syntax.purs
  src/IntervalArith/Approx/Approx.purs
  src/IntervalArith/Extended.purs
  src/Plot/RobustPlot.purs
  test/Expression/Differentiator/Differentiate.purs
  test/Expression/Parser/Parse.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/Expression/SubExpression/OrderDepencencies.purs
  test/Expression/SubExpression/SplitSubExpressions.purs
  test/Expression/SubExpression/SubExpressionToVariableMap.purs
  test/Expression/SubExpression/SubstituteSubExpressions.purs
Labels: enhancement
