Repository michalkonecny/robust-plots, pull requests merged in 2020-07, with the labels that each got.

#80 Added adaptive segmentation
  src/Components/AccuracyInput/AccuracyInput.purs
  src/Components/BatchInput/BatchInput.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Expression/Evaluator.purs
  src/Expression/Syntax.purs
  src/IntervalArith/Approx/Approx.purs
  src/Misc/Array.purs
  src/Misc/Queue.purs
  src/Plot/Commands.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
  src/Plot/PlotEvaluator.purs
  src/Plot/RobustPlot.purs
  src/Plot/Segments.purs
  test/Expression/Differentiator/Differentiate.purs
  test/Expression/Evaluator/Evaluate.purs
  test/Main.purs
  test/Misc/Array/Array.purs
  test/Misc/Array/Split.purs
  test/Misc/Misc.purs
  test/Plot/JobBatcher/AddPlot.purs
  test/Plot/JobBatcher/CancelAll.purs
  test/Plot/JobBatcher/HasJobs.purs
  test/Plot/JobBatcher/InitialJobQueue.purs
  test/Plot/JobBatcher/JobBatcher.purs
  test/Plot/JobBatcher/SetRunning.purs
  test/Plot/Plot.purs
  test/Plot/Segments/SegmentDomain.purs
  test/Plot/Segments/Segments.purs
Labels: enhancement

#83 Integrated bootstrap and added dynamic canvas
  index.html
  src/Components/AccuracyInput/AccuracyInput.purs
  src/Components/BatchInput/BatchInput.purs
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Canvas/Canvas.purs
  src/Components/Canvas/Controller.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  test/Plot/JobBatcher/CancelAll.purs
  test/Plot/JobBatcher/HasJobs.purs
  test/Plot/JobBatcher/SetRunning.purs
Labels: enhancement

#89 Added delete plot button and dynamic grid lines
  src/Components/Canvas/Canvas.purs
  src/Components/Canvas/Draw.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Misc/Array.purs
  src/Misc/Math.purs
  src/Misc/Number.purs
  src/Plot/GridLines.purs
  test/Misc/Math/Log10.purs
  test/Misc/Math/Math.purs
  test/Misc/Misc.purs
  test/Plot/GridLines/CalculateInterval.purs
  test/Plot/GridLines/GridLines.purs
  test/Plot/Plot.purs
  test/TestUtils.purs
Labels: enhancement, tech debt

#91 Moved bounds input and added expression name
  index.html
  src/Components/AccuracyInput/AccuracyInput.purs
  src/Components/BatchInput/BatchInput.purs
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/ExpressionManager/Types.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
Labels: enhancement

#95 Added accuracy per function and conditional robust plotting
  src/Components/AccuracyInput/AccuracyInput.purs
  src/Components/BatchInput/BatchInput.purs
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Canvas/Draw.purs
  src/Components/Checkbox/Checkbox.purs
  src/Components/Common/Action.purs
  src/Components/Common/ClassName.purs
  src/Components/ExpressionInput/Controller.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/ExpressionManager/Types.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
Labels: enhancement

#96 Fixed canvas scrolling and size ratio
  index.html
  src/Components/BoundsInput/BoundsInput.purs
  src/Components/Canvas/Canvas.purs
  src/Components/Canvas/Controller.purs
  src/Components/Common/HTML.purs
  src/Components/Main/Action.purs
  src/Components/Main/Main.purs
  test/Plot/JobBatcher/CancelAll.purs
  test/Plot/JobBatcher/HasJobs.purs
  test/Plot/JobBatcher/SetRunning.purs
Labels: bug, enhancement

#97 Support basic trigonometric functions
  package.json
  src/Components/ExpressionInput/Controller.purs
  src/Expression/Differentiator.purs
  src/Expression/Evaluator.purs
  src/IntervalArith/Approx/Approx.purs
  src/IntervalArith/Approx/Pi.purs
  src/IntervalArith/Approx/SinCos.purs
  src/IntervalArith/Approx/Taylor.purs
  src/IntervalArith/Misc.purs
  src/Misc/LazyList/LazyList.purs
  src/Misc/LazyList/NumberSequences.purs
  src/Misc/Tuple22.purs
  src/Plot/PlotEvaluator.purs
  src/Plot/RoughPlot.purs
  test/Expression/Differentiator/Differentiate.purs
  test/Expression/Evaluator/Evaluate.purs
  test/Expression/Evaluator/RoughEvaluate.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/IntervalArith/Approx/Approx.purs
  test/IntervalArith/Approx/Pi.purs
  test/IntervalArith/Approx/SinCos.purs
  test/IntervalArith/Misc.purs
Labels: enhancement

#99 Approx exp, log, power
  src/Expression/Evaluator.purs
  src/IntervalArith/Approx/ExpLog.purs
  src/IntervalArith/Approx/Pi.purs
  src/IntervalArith/Approx/Sqrt.purs
  src/IntervalArith/Dyadic.purs
  src/Misc/LazyList/NumberSequences.purs
  test/Expression/Evaluator/Evaluate.purs
  test/IntervalArith/Approx/Approx.purs
  test/IntervalArith/Approx/ExpLog.purs
  test/IntervalArith/Approx/Power.purs
  test/IntervalArith/Approx/Sqrt.purs
Labels: enhancement

#100 Added labels and navbar
  src/Components/Canvas/Canvas.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Draw/Commands.purs
  src/Misc/Array.purs
  src/Misc/Maybe.purs
  src/Plot/Helper.purs
  src/Plot/Label.purs
  src/Plot/RoughPlot.purs
  test/Plot/Label/FixLabelledPositions.purs
  test/Plot/Label/Label.purs
  test/Plot/Label/ToRoughLabelPosition.purs
  test/Plot/Plot.purs
Labels: enhancement

#105 Added end of file check to parser
  src/Expression/Parser.purs
  test/Expression/Parser/Parse.purs
Labels: bug

#107 Improve enclosures
  src/Components/Main/Helper.purs
  src/IntervalArith/Approx/Approx.purs
  src/Misc/Debug.purs
  src/Plot/RobustPlot.purs
  src/Plot/Segments.purs
Labels: enhancement

#108 Added progress bar, spinner and footer
  index.html
  src/Components/Common/Styles.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Components/ProgressBar/ProgressBar.purs
  src/Misc/Queue.purs
  src/Plot/JobBatcher.purs
Labels: enhancement

#109 Added default example functions
  src/Components/Common/Action.purs
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/ExpressionManager/ExpressionManager.purs
Labels: enhancement

#111 Added performance tracking
  src/Components/ExpressionManager/ExpressionManager.purs
  test/FFI/Timer.js
  test/FFI/Timer.purs
  test/IntervalArith/Approx/Pi.purs
Labels: enhancement

#113 Automatic differentiation
  src/Components/ExpressionInput/Controller.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Expression/Differentiator.purs
  src/Expression/Evaluate/AutomaticDifferentiator.purs
  src/Expression/Evaluate/OperatorClasses.purs
  src/Expression/Evaluator.purs
  src/Expression/Parser.purs
  src/Expression/Simplifier.purs
  src/Expression/Syntax.purs
  src/IntervalArith/Approx/ExpLog.purs
  src/IntervalArith/Approx/NumOrder.purs
  src/IntervalArith/Approx/SinCos.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotEvaluator.purs
  src/Plot/RobustPlot.purs
  src/Plot/RoughPlot.purs
  src/Plot/Segments.purs
  test/Expression/Differentiator/Differentiate.purs
  test/Expression/Differentiator/Differentiator.purs
  test/Expression/Evaluate/AutomaticDifferentiation/AutomaticDifferentiation.purs
  test/Expression/Evaluate/AutomaticDifferentiation/EvaluateDerivative.purs
  test/Expression/Evaluate/AutomaticDifferentiation/EvaluateDerivative2.purs
  test/Expression/Evaluate/Evaluate.purs
  test/Expression/Evaluator/Evaluate.purs
  test/Expression/Evaluator/Evaluator.purs
  test/Expression/Evaluator/RoughEvaluate.purs
  test/Expression/Expression.purs
  test/Expression/SubExpression/JoinCommonSubExpressions.purs
  test/Plot/Segments/SegmentDomain.purs
  test/TestUtils.purs
Labels: enhancement

#115 Async segmentation and UI tweaks
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Components/ProgressBar/ProgressBar.purs
  src/Plot/JobBatcher.purs
Labels: enhancement

#121 Fix accuracy issues in sqrt(x^2)
  src/Expression/Evaluate/AutomaticDifferentiator.purs
  src/IntervalArith/Approx/Sqrt.purs
  src/Plot/Commands.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
  src/Plot/RobustPlot.purs
  src/Plot/Segments.purs
  test/Plot/Segments/SegmentDomain.purs
  test/TestUtils.purs
Labels: bug, enhancement

#122 Fixes to min, max, abs
  src/Expression/Evaluate/AutomaticDifferentiator.purs
  src/Expression/Evaluate/OperatorClasses.purs
  src/Plot/RobustPlot.purs
  src/Plot/Segments.purs
Labels: bug

#124 Power performance
  src/Expression/Evaluate/AutomaticDifferentiator.purs
  src/Expression/Evaluate/OperatorClasses.purs
  src/Expression/Simplifier.purs
  src/Expression/Syntax.purs
  src/IntervalArith/Misc.purs
  test/IntervalArith/Approx/Power.purs
Labels: performance

#125 New examples, enclosure improvements, adaptive precision
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/Main/Helper.purs
  src/Plot/JobBatcher.purs
  src/Plot/RobustPlot.purs
  src/Plot/Segments.purs
  test/Plot/Segments/SegmentDomain.purs
Labels: enhancement

#126 Added global error handling and status indicator
  src/Components/ExpressionInput/ExpressionInput.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
Labels: enhancement

#127 UI tidy up, version 0.1.0
  package.json
  src/Components/BatchInput/BatchInput.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  test/IntervalArith/Approx/Pi.purs
Labels: enhancement

#129 Added rough parametric plots
  src/Components/ExpressionInput/Controller.purs
  src/Components/ExpressionInput/FunctionExpressionInput/FunctionExpressionInput.purs
  src/Components/ExpressionInput/ParametricExpressionInput/ParametricExpressionInput.purs
  src/Components/ExpressionManager/ExpressionManager.purs
  src/Components/ExpressionManager/Types.purs
  src/Components/Main/Action.purs
  src/Components/Main/Helper.purs
  src/Components/Main/Main.purs
  src/Components/Main/Types.purs
  src/Expression/Error.purs
  src/Misc/Array.purs
  src/Misc/ExpectAff.purs
  src/Plot/Commands.purs
  src/Plot/JobBatcher.purs
  src/Plot/PlotController.purs
  src/Plot/RobustPlot.purs
  src/Plot/RoughFunctionPlot.purs
  src/Plot/RoughParametricPlot.purs
  src/ViewModels/Expression/Common.purs
  src/ViewModels/Expression/Draw.purs
  src/ViewModels/Expression/Expression.purs
  src/ViewModels/Expression/Function/Draw.purs
  src/ViewModels/Expression/Function/Function.purs
  src/ViewModels/Expression/Helper.purs
  src/ViewModels/Expression/Job.purs
  src/ViewModels/Expression/Parametric/Draw.purs
  src/ViewModels/Expression/Parametric/Parametric.purs
  src/ViewModels/Expression/Unsafe.purs
  test/Plot/Segments/SegmentDomain.purs
Labels: enhancement

#133 Added parametric robust box plotting
  src/Plot/Commands.purs
  src/Plot/FunctionSegments.purs
  src/Plot/JobBatcher.purs
  src/Plot/Parametric.purs
  src/Plot/ParametricSegments.purs
  src/Plot/PlotController.purs
  src/Plot/RobustFunctionPlot.purs
  src/Plot/RobustParametricPlot.purs
  src/Plot/RoughParametricPlot.purs
  src/ViewModels/Expression/Parametric/Draw.purs
  test/Plot/FunctionSegments/FunctionSegments.purs
  test/Plot/FunctionSegments/SegmentDomain.purs
  test/Plot/Plot.purs
Labels: enhancement

#134 Added benchmark
  .gitignore
  benchmark/Main.purs
  benchmark/Plotter.purs
  benchmark/Run.js
  package.json
  packages.dhall
  spago.dhall
  src/Plot/FunctionSegments.purs
  src/Plot/RobustFunctionPlot.purs
Labels: enhancement
